### ISSUE TITLE
Build fails on Ubuntu / Windows machine without Helvetica

### ISSUE THREAD

**Issue by majcote** [clearpathrobotics/clearpath-latex#1]

**Comment by mikepurvis** [comment]
Wondering if there's some way we can parameterize the LaTeX class to optionally switch out the proprietary fonts.

Really, an env var would be ideal for this, though it doesn't seem there's a reasonable cross-platform env var solution for LaTeX.

**Comment by dniewinski** [comment]
Super late to the game, but #2 tracks all fonts
